In [3]:
import numpy as np
import pandas as pd
data={'Overs':[2,6,8,10],'Score':[23,63,76,98]}
df=pd.DataFrame(data)
df

Overs  Score
0      2     23
1      6     63
2      8     76
3     10     98

In [4]:
df.Score

0    23
1    63
2    76
3    98
Name: Score, dtype: int64

In [6]:
from sklearn import linear_model
reg=linear_model.LinearRegression()
reg.fit(df.drop('Score',axis='columns'),df.Score)

LinearRegression()

In [7]:
reg.coef_

array([9.2])

In [8]:
reg.intercept_

5.200000000000017

In [9]:
reg.predict([[12]])

array([115.6])

In [10]:
reg.predict([[15]])

array([143.2])

In [11]:
reg.predict([[18]])

array([170.8])

In [12]:
reg.predict([[20]])

array([189.2])

In [ ]:
#Here the predicted score for 12th over is 115 runs
#The predicted score for 15th over is 143 runs
#the predicted score for 18th over is 170 runs
#the predicted score for last over is 189 runs